substitutions:
  rttti_gain: "1."

esphome:
  name: combadge
  friendly_name: ComBadge
  min_version: 2024.6.0
  name_add_mac_suffix: true  
  includes:
    - common/badgeID.h 
  project:
    name: LumenSoft.ComBadge 
    version: "0.25"

esp32:
  board: m5stack-atom
  framework:
    type: esp-idf
    version: 4.4.8

# This should point to the public location of this yaml file.
dashboard_import:
  package_import_url: github://lumensoft/combadge/combadge_va.yaml
  import_full_config: true

external_components:
  - source:
      type: git
      url: https://github.com/gnumpi/esphome_audio
      ref: main
    components: [ adf_pipeline, i2s_audio]
  - source:
      type: git
      url: https://github.com/nielsnl68/esphome
      ref: nvds-rtttl-restore-volume-gain
    components: [rtttl]
    refresh: 1min
  - source: github://pr#5814
    components: [ status_indicator, wifi ]

logger:
  level: debug

api:
  on_client_connected:
      - rtttl.play: "Intro:d=32,o=5,b=300:g#4,h4,d#4,2p." 

ota:
  - platform: esphome
    id: ota_esphome
    password: C0mB@dG3

wifi:
  on_connect:
    - delay: 5s  # Gives time for improv results to be transmitted
    - ble.disable:
  on_disconnect:
    - ble.enable:

# Sets up Bluetooth LE (Only on ESP32) to allow the user
# to provision wifi credentials to the device.
esp32_improv:
  authorizer: none
  status_indicator: improv_led

output:
  - platform: template
    id: improv_led
    type: float
    write_action:
      - if:
          condition:
            lambda: return ((state > 0) && (state < .4));
          then:
            - light.turn_off: led
          else:
            - light.turn_on:
                id: led
                red: 0%
                green: 30%
                blue: 30%
                brightness: 50%
                effect: none


i2s_audio:
  - id: i2s_dplx
    i2s_lrclk_pin: GPIO33
    i2s_bclk_pin: GPIO19
    access_mode: exclusive


adf_pipeline:
  - platform: i2s_audio
    type: audio_out
    id: adf_i2s_out
    i2s_audio_id: i2s_dplx
    i2s_dout_pin: GPIO22

    adf_alc: true
    #alc_max: 0.6

    sample_rate: 16000
    bits_per_sample: 16bit
    channel: right
    fixed_settings: false

  - platform: i2s_audio
    type: audio_in
    id: adf_i2s_in
    i2s_audio_id: i2s_dplx
    i2s_din_pin: GPIO23
    pdm: true
    bits_per_sample: 32bit
    channel: right
    fixed_settings: true

microphone:
  - platform: adf_pipeline
    id: echo_microphone
    keep_pipeline_alive: false
    pipeline:
      - adf_i2s_in
      - self

speaker:
  - platform: adf_pipeline
    id: adf_speaker
    keep_pipeline_alive: false
    pipeline:
      - self
      - adf_i2s_out

media_player:
  - platform: adf_pipeline
    id: adf_media_player
    name: none
    keep_pipeline_alive: false
    #announcement_audio:
    #  sample_rate: 16000
    #  bits_per_sample: 16
    #  num_channels: 1
    internal: false
    pipeline:
      - self
      - adf_i2s_out

voice_assistant:
  id: va
  microphone: echo_microphone
  speaker: adf_speaker

  noise_suppression_level: 2
  auto_gain: 31dBFS
  volume_multiplier: 4.0
  use_wake_word: false

  on_listening:
    - status.push: va_listening
  on_stt_vad_end:
    - status.push: va_stt_vad_end
  on_tts_start:
    - status.push: va_tts_start
  on_end:
    - wait_until:
        not:
          speaker.is_playing:
    - status.pop: va_tts_start
    - status.pop: va_stt_vad_end
    - status.pop: va_listening


  on_error:
    - status.push: va_error
    - rtttl.play: "TextAler:d=16,o=7,b=225:d,p,2g."
    - wait_until:
        not:
          speaker.is_playing:               
    - status.pop: va_error

  on_client_disconnected:
    - if:
        condition: voice_assistant.is_running
        then:
          - voice_assistant.stop:
          - status.pop: va_tts_start
          - status.pop: va_stt_vad_end
          - status.pop: va_listening

light:
  - platform: esp32_rmt_led_strip
    name: None
    id: led
    rgb_order: GRB
    pin: 27
    num_leds: 1
    rmt_channel: 0
    chipset: ws2812
    restore_mode: ALWAYS_OFF

    default_transition_length: 0s

    effects:
      - pulse:
          name: "Slow Pulse"
          transition_length: 250ms
          update_interval: 250ms
          min_brightness: 50%
          max_brightness: 100%
      - pulse:
          name: "Fast Pulse"
          transition_length: 100ms
          update_interval: 100ms
          min_brightness: 50%
          max_brightness: 100%
      - pulse:
          name: "Short long"
          transition_length: 50ms
          update_interval: 100ms
          min_brightness: 00%
          max_brightness: 50%          
      - random:
            name: "waiting"
      - flicker:    
            name: "idle"
      - strobe:
            name: ErrorStrobe
            colors:
              - state: true
                brightness: 100%
                red: 100%
                green: 0%
                blue: 0%
                duration: 500ms
              - state: false
                duration: 250ms
              - state: true
                brightness: 100%
                red: 60%
                green: 0%
                blue: 0%
                duration: 500ms      

status_indicator:
  on_turn_off: #Manditory
    - light.turn_on:
        id: led
        red: 0%
        green: 20%
        blue: 0%
        brightness: 50%
        effect: idle

  on_app_error:
    then:
    - light.turn_on:
        id: led
        red: 100%
        green: 0%
        blue: 0%
        brightness: 50%
        effect: none

  on_app_warning:
    then:
    - light.turn_on:
        id: led
        red: 100%
        green: 0%
        blue: 0%
        brightness: 50%
        effect: ErrorStrobe

  on_wifi_ap_enabled:
    then:
    - light.turn_on:
        id: led
        red: 0%
        green: 30%
        blue: 30%
        brightness: 50%
        effect: Short long

  on_network_disconnected:
    then:
    - light.turn_on:
        id: led
        red: 100%
        green: 0%
        blue: 50%
        brightness: 50%
        effect: Fast Pulse

  on_api_disconnected:
    then:
    - light.turn_on:
        id: led
        red: 100%
        green: 100%
        blue: 0%
        brightness: 50%
        effect: Fast Pulse

  on_custom_status:
    - trigger_id: va_listening
      priority: 1
      then:
        - light.turn_on:
            id: led
            red: 0%
            green: 0%
            blue: 100%
            brightness: 50%
            effect: Slow Pulse
    - trigger_id: va_stt_vad_end
      priority: 2
      group: va_active
      then:
        - light.turn_on:
            id: led
            red: 0%
            green: 0%
            blue: 100%
            brightness: 100%
            effect: Fast Pulse 

    - trigger_id: va_tts_start
      priority: 2
      group: va_active
      then:
        - light.turn_on:
            id: led
            red: 0%
            green: 100%
            blue: 100%
            brightness: 100%
            effect: none
    - trigger_id: va_error
      priority: 3
      then:
        - light.turn_on:
            id: led
            red: 100%
            green: 100%
            blue: 50%
            brightness: 100%
            effect: Fast pulse
    - trigger_id: test_button
      priority: 1
      then:
        - light.turn_on:
            id: led
            brightness: 50%
            red: 00%
            green: 0%
            blue: 50%
            effect: waiting

button:
  - platform: factory_reset
    id: factory_reset_btn
    name: Factory reset
    disabled_by_default: true
    entity_category: diagnostic

esp32_touch:
  setup_mode: false
  iir_filter: 10ms

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO39
      inverted: true
    name: test button
    disabled_by_default: true
    entity_category: diagnostic
    id: echo_button

    on_click:
      - status.push: test_button
      - rtttl.play: "StarTrek:d=4,o=5,b=63:8f.,16a#,d#.6,8d6,16a#.,16g.,16c.6,f6" 
      - wait_until:
          not:
            speaker.is_playing:          
      - status.pop: test_button

  - platform: esp32_touch
    pin: T9
    threshold: 900
    name: action button
    disabled_by_default: true
    entity_category: diagnostic
    id: echo_button2
    on_press: 
      then:
        status.push: test_button
    on_release:
      then:
        status.pop: test_button

    on_multi_click:
      - timing:
          - ON for at least 150ms
          - OFF for at least 50ms
        then:
          - if:
              condition: api.connected
              then:
                - if:
                    condition: voice_assistant.is_running
                    then:
                      - voice_assistant.stop:
                      - status.pop: va_tts_start
                      - status.pop: va_stt_vad_end
                      - status.pop: va_listening
                      - rtttl.play: "Schooier:d=4,o=5,b=225:d,e4."
                      - wait_until:
                          not:
                            speaker.is_playing:           
                    else:
                      - rtttl.play: "KnockKno:d=32,o=5,b=300:e4,g6." 
                      - wait_until:
                          not:
                            speaker.is_playing:     
                      - voice_assistant.start_continuous:
              else:
                - rtttl.play: "Fly:d=32,o=5,b=300:f2,f#2,4p."

      - timing:
          - ON for at least 10s
        then:
          - rtttl.play: "PagerSou:d=16,o=5,b=200:d6,8p,d6,8p,f6,32p,d6"
          - wait_until:
              not:
                speaker.is_playing:            
          - button.press: factory_reset_btn

rtttl:
  speaker: adf_speaker
  id: my_rtttl
  gain: 1.0

sensor:
  - platform: internal_temperature
    name: "Internal Temperature"

# StarTrek:d=32,o=6,b=225:16c#,d,d#,4e.,d#,d,8c#
# Trio:d=32,o=5,b=300:c#4,p,f4,c#4,g#4,p,2p.
# PagerSou:d=16,o=5,b=200:d6,8p,d6,8p,f6,32p,d6
# De:d=4,o=5,b=200:g,8f,8b,a,b,p
# StarTrek:d=4,o=5,b=63:8f.,16a#,d#.6,8d6,16a#.,16g.,16c.6,f6
# Siren:d=32,o=5,b=300:a2,p,a#2,p,h2,p,c4,p,c#4,p,d4,p,d#4,p,e4,p,f4,p,f#4,p,8p.
# Morning:d=4,o=6,b=80:8g,8e,8d,8c,8d,8e,8g,8e,8d,8c,8d,8e,8g,8e,8g,8a,8e,8a,8g,8e,8d,2c
# Triple:d=8,o=5,b=635:c,e,g,c,e,g,c,e,g,c6,e6,g6,c6,e6,g6,c6,e6,g6,c7,e7,g7,c7,e7,g7,c7,e7,g7
