#pragma once

#include "Version.h"

#ifndef VERSION
#define VERSION "0.0.0"
#endif


/// Request message codes :

#define NOWTALK_CLIENT_PING 0x01
#define NOWTALK_SERVER_PONG 0x02
#define NOWTALK_SERVER_REQUEST_DETAILS 0x03
#define NOWTALK_CLIENT_DETAILS 0x04
#define NOWTALK_CLIENT_NEWPEER 0x05

#define NOWTALK_SERVER_ACCEPT 0x07

#define NOWTALK_SERVER_NEW_NAME 0x0d
#define NOWTALK_SERVER_NEW_IP 0x0e

#define NOWTALK_CLIENT_ACK 0x10
#define NOWTALK_CLIENT_NACK 0x11

#define NOWTALK_CLIENT_START_CALL 0x30
#define NOWTALK_SERVER_SEND_PEER 0x31
#define NOWTALK_SERVER_PEER_GONE 0x32
#define NOWTALK_SERVER_OVER_WEB 0x33

#define NOWTALK_CLIENT_REQUEST 0x37
#define NOWTALK_CLIENT_RECEIVE 0x38
#define NOWTALK_CLIENT_CLOSED 0x39

#define NOWTALK_STREAM_START 0x3d
#define NOWTALK_STREAM_DATA 0x3e
#define NOWTALK_STREAM_END 0x3f


#define NOWTALK_CLIENT_HELPSOS 0xff



#define NOWTALK_STATUS_GONE 0x00
#define NOWTALK_STATUS_ALIVE 0x01
#define NOWTALK_STATUS_GUEST 0x02

#define NOWTALK_PEER_MEMBER 0x10
#define NOWTALK_PEER_FRIEND 0x20
#define NOWTALK_PEER_BLOCKED 0x80

#endif
